baseurl: ''
title: Electography
subtitle: Electoral Geography
author: Samual Black
simple_search: http://google.com/search
description: Posts about elections and geography
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:year-:month-:day/:title
timezone: Europe/London
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: main
